### ISSUE TITLE
Failure on 32-bits architecture with Python 3

### ISSUE THREAD

**Issue by ViviCoder** [weaverba137/pydl#20] opened 2016-12-21 12:04 UTC
On a 32-bits architecture, with Python 3.5.2, I obtain the following failure:
```
=================================== FAILURES ===================================
___________________________ [doctest] pydl.uniq.uniq ___________________________
031 
032     References
033     ----------
034     http://www.exelisvis.com/docs/UNIQ.html
035 
036     Examples
037     --------
038     >>> import numpy as np
039     >>> from pydl import uniq
040     >>> uniq(np.sort(np.array([ 1, 2, 3, 1, 5, 6, 1, 7, 3, 2, 5, 9, 11, 1 ])))
Expected:
    array([ 3,  5,  7,  9, 10, 11, 12, 13])
Got:
    array([ 3,  5,  7,  9, 10, 11, 12, 13], dtype=int32)
```

**Comment by weaverba137** [comment] 2016-12-21 17:06
What PyDL version please?

**Comment by ViviCoder** [comment] 2016-12-21 17:35
@weaverba137 I obtained this failure with version 0.5.3.

**Comment by weaverba137** [comment] 2016-12-21 17:52
OK, and how exactly did you run this test?  `python setup.py test` or something else?

**Comment by ViviCoder** [comment] 2016-12-21 18:08
Indeed, I used python setup.py test.

**Comment by weaverba137** [comment] 2017-01-10 00:29
I'm not able to reproduce this in my own 32-bit test system.  Could you please provide more details about exactly how you set up your 32-bit environment?

**Comment by ViviCoder** [comment] 2017-01-10 14:28
I use pbuilder, that creates a clean chroot environment in which Debian packages can be built.

**Comment by weaverba137** [comment] 2017-01-10 16:25
That's not exactly what I meant.  Please specify the *versions* of all software associated with this test, in addition to the framework in which you performed the test.  This includes OS version, Python version, Numpy version, Scipy version, etc.

In general, please do this for *all* bug reports.

**Comment by ViviCoder** [comment] 2017-01-10 16:37
```
platform linux -- Python 3.5.3rc1, pytest-2.8.3, py-1.4.30, pluggy-0.3.1

Running tests with pydl version 0.5.3.
Running tests in lib.linux-x86_64-3.5/pydl docs.

Date: 2017-01-10T14:19:01

Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-stretch-sid

Executable: /usr/bin/python3

Full Python Version: 
3.5.3rc1 (default, Jan  3 2017, 04:40:57) 
[GCC 6.3.0 20161229]

encodings: sys: utf-8, locale: ANSI_X3.4-1968, filesystem: ascii
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.12.0rc2
Scipy: 0.18.1
Matplotlib: not available
Astropy: 1.3
PyDL: 0.5.3
Using Astropy options: remote_data.
```
My machine is 64 bits, but the chroot environment is 32 bits.

**Comment by weaverba137** [comment] 2017-01-10 16:46
Good that's what I need.  Until now there was no mention that you were using Numpy 1.12.0rc2.  That's kind of important.

**Comment by weaverba137** [comment] 2017-01-10 17:49
This is now fixed in the hmf-object branch and will be incorporated into the next release.

**Closed by weaverba137** 2017-01-10 17:49 UTC
Labels: bug
